from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal

from app.agents import AGENT_SYSTEM_PROMPTS
from app.services.quality import estimate_confidence


@dataclass(frozen=True)
class Citation:
    source_name: str
    source_url: str
    published_at: str
    retrieved_at: str
    confidence_score: Decimal


@dataclass(frozen=True)
class EvidenceItem:
    id: str
    text: str
    citation: Citation
    fact_value: str | None = None
    formula: str | None = None


@dataclass(frozen=True)
class AgentOutput:
    agent_name: str
    facts: list[str]
    calculations: list[str]
    assumptions: list[str]
    interpretations: list[str]
    risks: list[str]
    open_questions: list[str]
    citations: list[str]
    confidence_score: Decimal


def format_citation(citation: Citation) -> str:
    return (
        f"{citation.source_name} | {citation.source_url} | published={citation.published_at} "
        f"| retrieved={citation.retrieved_at} | confidence={citation.confidence_score}"
    )


def retrieve_evidence(items: list[EvidenceItem], query: str) -> list[EvidenceItem]:
    terms = {term.lower() for term in query.split() if len(term) > 2}
    if not terms:
        return items
    return [item for item in items if terms.intersection(item.text.lower().split())]


def detect_conflicting_evidence(items: list[EvidenceItem]) -> list[str]:
    by_fact: dict[str, set[str]] = {}
    for item in items:
        if item.fact_value is None:
            continue
        by_fact.setdefault(item.text, set()).add(item.fact_value)
    return [text for text, values in by_fact.items() if len(values) > 1]


def run_company_research_agent(evidence: list[EvidenceItem]) -> AgentOutput:
    citations = [format_citation(item.citation) for item in evidence]
    confidence = estimate_confidence([item.citation.confidence_score for item in evidence], 0)
    return AgentOutput(
        agent_name="company_research",
        facts=[item.text for item in evidence],
        calculations=[item.formula for item in evidence if item.formula],
        assumptions=[],
        interpretations=["Interpretations are marked as provisional until reviewed."],
        risks=["Customer concentration and margin normalization require explicit evidence review."],
        open_questions=[
            "Which customer concentration disclosures are available in the latest filing?"
        ],
        citations=citations,
        confidence_score=confidence,
    )


def orchestrate_research_report(evidence: list[EvidenceItem]) -> dict[str, object]:
    company_output = run_company_research_agent(evidence)
    conflicts = detect_conflicting_evidence(evidence)
    return {
        "agents": AGENT_SYSTEM_PROMPTS,
        "facts": company_output.facts,
        "calculations": company_output.calculations,
        "assumptions": [
            "Bull/Base/Bear scenarios are demo assumptions unless backed by stored assumptions."
        ],
        "interpretation": company_output.interpretations,
        "risks": company_output.risks,
        "open_questions": company_output.open_questions,
        "citations": company_output.citations,
        "conflicting_evidence": conflicts,
        "confidence_score": company_output.confidence_score,
        "risk_audit": {
            "requires_human_review": bool(conflicts),
            "notes": "No buy/sell language is generated by this deterministic orchestrator.",
        },
    }
