export type DemoResearchResponse = {
  demo_notice: string;
  company?: {
    name: string;
    ticker: string;
    archetype?: {
      name: string;
    };
  };
  research_output: {
    executive_summary: string;
    financial_quality?: Array<{
      metric: string;
      status: string;
      value: string | number | null;
      unit: string;
      formula: string;
      message?: string | null;
    }>;
    risks: string[];
    catalysts?: string[];
    bull_base_bear: Record<string, Array<string | number>>;
    valuation: Record<string, unknown>;
    key_assumptions?: Record<string, string>;
    sources_and_confidence?: string[];
  };
  agent_report?: {
    facts: string[];
    calculations: string[];
    risks: string[];
    open_questions: string[];
    confidence_score: string | number;
  };
  quality_issues?: Array<{
    severity: string;
    category: string;
    message: string;
    needs_human_review: boolean;
  }>;
};

export type DemoIndustryResponse = {
  demo_notice: string;
  industry: string;
  value_chain_map?: Record<string, string[]>;
  market_size_growth_drivers?: string[];
  competitive_landscape?: string[];
  cycle_indicators: string[];
  three_year_risks_catalysts?: {
    risks: string[];
    catalysts: string[];
  };
  tracking_metrics: string[];
};

export type DemoComparisonResponse = {
  demo_notice: string;
  comparison: string;
  score_matrix: Array<{
    ticker: string;
    scores: Record<string, number>;
  }>;
};

export type DemoBundle = {
  nvidia: DemoResearchResponse;
  industry: DemoIndustryResponse;
  comparison: DemoComparisonResponse;
  source: "api" | "synthetic_fallback";
};

export const fallbackDemoBundle: DemoBundle = {
  source: "synthetic_fallback",
  nvidia: {
    demo_notice:
      "Synthetic demo data for workflow testing only. Not production market data and not investment advice.",
    company: {
      name: "Nvidia",
      ticker: "NVDA",
      archetype: { name: "Semiconductor" }
    },
    research_output: {
      executive_summary:
        "Demo workflow: demand durability depends on AI capex breadth, margin mix, and customer concentration evidence.",
      financial_quality: [
        {
          metric: "revenue_growth",
          status: "ok",
          value: "0.4118",
          unit: "percent",
          formula: "(current_revenue - previous_revenue) / previous_revenue"
        },
        {
          metric: "gross_margin",
          status: "ok",
          value: "0.7500",
          unit: "ratio",
          formula: "gross_profit / revenue"
        },
        {
          metric: "free_cash_flow_margin",
          status: "ok",
          value: "0.4833",
          unit: "ratio",
          formula: "free_cash_flow / revenue"
        },
        {
          metric: "inventory_turnover",
          status: "unavailable",
          value: null,
          unit: "n/a",
          formula: "cogs / average_inventory",
          message: "无法可靠计算：Missing cost_of_goods_sold or average_inventory."
        }
      ],
      risks: [
        "AI capex digestion risk",
        "gross margin normalization risk",
        "hyperscaler customer concentration risk",
        "export-control and supply-chain risk"
      ],
      catalysts: ["new platform cycle", "broader enterprise inference adoption", "supply expansion"],
      bull_base_bear: {
        bear: [60900, 63945, 67142.25],
        base: [67280, 78044.8, 90531.968],
        bull: [73080, 92080.8, 116021.808]
      },
      valuation: {
        dcf: "DCF bull/base/bear scenarios generated by deterministic Python service.",
        ev_sales: "EV/Sales multiple view",
        pe: "PE multiple view"
      },
      key_assumptions: {
        bear_growth: "5% FCF CAGR for three demo years",
        base_growth: "16% FCF CAGR for three demo years",
        bull_growth: "26% FCF CAGR for three demo years"
      },
      sources_and_confidence: [
        "InsightOS Synthetic Nvidia Fixture | internal://insightos/demo/nvidia | published=2026-06-23 | retrieved=2026-06-23T00:00:00Z | confidence=0.9000"
      ]
    },
    agent_report: {
      facts: [
        "Demo fixture indicates AI accelerator demand remains strong but depends on hyperscaler capex.",
        "Demo fixture separates data center revenue quality from one-time inventory fill."
      ],
      calculations: ["gross_profit / revenue"],
      risks: ["Customer concentration and margin normalization require explicit evidence review."],
      open_questions: [
        "Which customer concentration disclosures are available in the latest filing?"
      ],
      confidence_score: "0.9000"
    },
    quality_issues: [
      {
        severity: "medium",
        category: "calculation_gap",
        message: "Inventory turnover is unavailable because working-capital inputs are missing.",
        needs_human_review: false
      }
    ]
  },
  industry: {
    demo_notice:
      "Synthetic demo data for workflow testing only. Not production market data and not investment advice.",
    industry: "Global Semiconductor Equipment",
    value_chain_map: {
      upstream: ["precision components", "optics", "vacuum systems", "specialty materials"],
      midstream: ["lithography", "etch", "deposition", "metrology", "inspection"],
      downstream: ["foundries", "memory makers", "IDMs", "advanced packaging"]
    },
    market_size_growth_drivers: [
      "advanced-node capex",
      "AI accelerator demand",
      "memory technology transitions",
      "regional fab localization"
    ],
    competitive_landscape: [
      "high technical barriers",
      "installed-base service revenue",
      "export-control segmentation"
    ],
    cycle_indicators: [
      "book-to-bill",
      "wafer fab equipment spend",
      "memory pricing",
      "foundry utilization"
    ],
    three_year_risks_catalysts: {
      risks: ["capex digestion", "export restrictions", "memory downturn"],
      catalysts: ["advanced packaging", "HBM demand", "fab localization subsidies"]
    },
    tracking_metrics: ["book-to-bill", "lead times", "foundry utilization", "memory ASP"]
  },
  comparison: {
    demo_notice:
      "Synthetic demo data for workflow testing only. Not production market data and not investment advice.",
    comparison: "Microsoft vs Google vs Amazon",
    score_matrix: [
      {
        ticker: "MSFT",
        scores: { cloud_growth: 82, ai_capex: 70, fcf: 86, valuation: 60, moat: 88 }
      },
      {
        ticker: "GOOGL",
        scores: { cloud_growth: 75, ai_capex: 76, fcf: 90, valuation: 68, moat: 86 }
      },
      {
        ticker: "AMZN",
        scores: { cloud_growth: 78, ai_capex: 82, fcf: 74, valuation: 62, moat: 84 }
      }
    ]
  }
};

export function getApiBaseUrl() {
  return process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000";
}

export async function fetchJson<T>(path: string): Promise<T> {
  const response = await fetch(`${getApiBaseUrl()}${path}`, {
    cache: "no-store"
  });
  if (!response.ok) {
    throw new Error(`Request failed: ${path}`);
  }
  return response.json() as Promise<T>;
}

export async function fetchDemoBundle(): Promise<DemoBundle> {
  try {
    const [nvidia, industry, comparison] = await Promise.all([
      fetchJson<DemoResearchResponse>("/api/demo/research/nvidia"),
      fetchJson<DemoIndustryResponse>("/api/demo/industry/semiconductor-equipment"),
      fetchJson<DemoComparisonResponse>("/api/demo/comparison/cloud-platforms")
    ]);
    return { nvidia, industry, comparison, source: "api" };
  } catch {
    return fallbackDemoBundle;
  }
}
